# Generated by Django 4.2 on 2024-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tes',
            name='test2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
