# Generated by Django 4.2 on 2024-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_tes_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tes',
            name='test3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tes',
            name='test4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
